@echo off

:: Change to the specified directory, or the directory of the batch file if none specified
set "PREV_DIR=%CD%"
if "%~1"=="" (cd /d "%~dp0") else (cd /d "%~1")

:: Define ESC character for ANSI color codes
for /f %%a in ('echo prompt $E^| cmd') do set "ESC=%%a"

:: Make sure verify.tool is available
dotnet tool restore
if %errorlevel% NEQ 0 goto error

:: Automatically accept any changes to snapshots generated by the tests, if any.
dotnet verify accept -y
if %errorlevel% NEQ 0 goto error
echo %ESC%[32mVerified public API update succeeded!%ESC%[0m
set "EXIT_CODE=0"
goto end

:error
set "EXIT_CODE=%errorlevel%"
echo %ESC%[31mVerified public API update failed!%ESC%[0m

:end
cd /d "%PREV_DIR%"
exit /b %EXIT_CODE%
