# Pipelines runs only on branches and tags.
# Disable merge request pipelines, pipelines for merge results and merge trains.
include:
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'
  - project: 'Sharpmake/SharpmakeExtended'
    file: 'build/sharpmake-ci.yml'
  # WARNING: When this include is modified, we also need to modifify the corresponding include in Get-SamplesPipeline.ps1.
  - project: 'ubi/runner/ci/templates'
    file: 'ubi_runner.yml'
    ref: '1.0.7'

stages:
  - build
  - test
  - validation
  - deploy

default:
  tags:
    - square_windows

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  DOTNET_NOLOGO: "true"
  DOTNET_CLI_UI_LANGUAGE: "en"

#############
# Stage Build: compile sharpmake solution on all targets, keep the binaries for further steps.

.compilation:base:
  stage: build
  
  parallel:
    matrix:
    - configuration: [debug, release]
  script:
    - dotnet build Sharpmake.sln -c $configuration -bl:Sharpmake_$configuration.binlog -clp:ForceConsoleColor
  artifacts:
    untracked: true
    expire_in: 1 day

compilation:windows:
  extends: .compilation:base

compilation:mac:
  extends:
    - .compilation:base
    - .ubi_runner_mac

compilation:linux:
  extends: .compilation:base
  tags: [square-linux-k8s-compil]
  image: mcr.microsoft.com/dotnet/sdk:8.0

generate_samples_pipeline:
  stage: build
  script: |
    pwsh -Command {
      Install-Module -Name powershell-yaml -RequiredVersion 0.4.7 -Force
     .\.gitlab\Get-SamplesPipeline.ps1 | Tee-Object -FilePath .gitlab/samples.yml
    }
  artifacts:
    paths:
    - .gitlab/samples.yml
    expire_in: 1 day

#############
# Stage Tests: run unit, regression, functional, and public API tests.

.test_base:
  stage: test
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 1 day

# Unit tests
.unit_test_base:
  extends: .test_base
  script:
    - dotnet test Sharpmake.UnitTests\Sharpmake.UnitTests.csproj --no-build -c $configuration

unit_test:debug:
  extends: .unit_test_base
  needs:
  - "compilation:windows: [debug]"
  variables:
    configuration: "debug"

unit_test:release:
  extends: .unit_test_base
  needs:
    - "compilation:windows: [release]"
  variables:
    configuration: "release"

# Regression tests
regression_test:
  extends: .test_base
  script:
  - python regression_test.py
  needs:
  - "compilation:windows: [release]"

# Functional tests
functional_test:
  extends: .test_base
  script:
  - python functional_test.py
  needs:
  - "compilation:windows: [release]"

# Public API tests
public_api_test:
  extends: .test_base
  script:
  - dotnet test Sharpmake.PublicApiTests/Sharpmake.PublicApiTests.csproj --no-build -c release
  needs:
  - "compilation:windows: [release]"

#############
# Samples
#############
samples:
  stage: test
  trigger:
    include:
    - artifact: .gitlab/samples.yml
      job: generate_samples_pipeline
    strategy: depend
    # Do not forward any variables to the child pipeline.
    # It can cause conflicts with macOS templates used in the child pipeline.
    forward:
      pipeline_variables: false
      yaml_variables: false

